"""setId do projeto → nome(s) do set no TCGplayer (subsets incluídos)."""
M={
'me55':['ME: 30th Celebration'],'me55c':['ME: 30th Celebration Classic Collection'],
'me5':['ME05: Pitch Black'],'me4':['ME04: Chaos Rising'],'me3':['ME03: Perfect Order'],
'me2pt5':['ME: Ascended Heroes'],'me2':['ME02: Phantasmal Flames'],'me1':['ME01: Mega Evolution'],
'zsv10pt5':['SV: Black Bolt'],'rsv10pt5':['SV: White Flare'],'sv10':['SV10: Destined Rivals'],
'sv9':['SV09: Journey Together'],'sv8pt5':['SV: Prismatic Evolutions'],'sv8':['SV08: Surging Sparks'],
'sv7':['SV07: Stellar Crown'],'sv6pt5':['SV: Shrouded Fable'],'sv6':['SV06: Twilight Masquerade'],
'sv5':['SV05: Temporal Forces'],'sv4pt5':['SV: Paldean Fates'],'sv4':['SV04: Paradox Rift'],
'sv3pt5':['SV: Scarlet & Violet 151'],'sv3':['SV03: Obsidian Flames'],'sv2':['SV02: Paldea Evolved'],
'sv1':['SV01: Scarlet & Violet Base Set'],
'swsh12pt5':['SWSH: Crown Zenith'],'swsh12pt5gg':['SWSH: Crown Zenith: Galarian Gallery','SWSH: Crown Zenith'],
'swsh12':['SWSH12: Silver Tempest'],'swsh12tg':['SWSH12: Silver Tempest Trainer Gallery','SWSH12: Silver Tempest'],
'swsh11':['SWSH11: Lost Origin'],'swsh11tg':['SWSH11: Lost Origin Trainer Gallery','SWSH11: Lost Origin'],
'pgo':['Pokemon GO'],
'swsh10':['SWSH10: Astral Radiance'],'swsh10tg':['SWSH10: Astral Radiance Trainer Gallery','SWSH10: Astral Radiance'],
'swsh9':['SWSH09: Brilliant Stars'],'swsh9tg':['SWSH09: Brilliant Stars Trainer Gallery','SWSH09: Brilliant Stars'],
'swsh8':['SWSH08: Fusion Strike'],'cel25':['Celebrations'],'cel25c':['Celebrations: Classic Collection'],
'swsh7':['SWSH07: Evolving Skies'],'swsh45':['Shining Fates'],'swsh45sv':['Shining Fates: Shiny Vault'],
'swsh4':['SWSH04: Vivid Voltage'],'swsh35':["Champion's Path"],'sm12':['SM - Cosmic Eclipse'],
'sm115':['Hidden Fates'],'sma':['Hidden Fates: Shiny Vault'],'sm9':['SM - Team Up'],'xy12':['XY - Evolutions'],
'ex7':['EX Team Rocket Returns'],'ex6':['EX FireRed & LeafGreen'],'ex1':['EX Ruby and Sapphire'],
'ecard3':['Skyridge'],'ecard2':['Aquapolis'],'ecard1':['Expedition'],'base6':['Legendary Collection'],
'neo4':['Neo Destiny'],'neo3':['Neo Revelation'],'neo2':['Neo Discovery'],'neo1':['Neo Genesis'],
'gym2':['Gym Challenge'],'gym1':['Gym Heroes'],'base5':['Team Rocket'],'base4':['Base Set 2'],
'base3':['Fossil'],'base2':['Jungle'],'base1':['Base Set'],
}
